#!/usr/bin/python
# -*- coding: utf-8 -*-

"""
Create a new note from the command-line
"""

# tell application "Notes"
#   make new note at folder "Notes" with properties {name:"Note", body:"body"}
# end tell

import sys
import os
import getopt
import tempfile
import subprocess


def esc(arg):

  buf = ''
  for i in arg:
    if (i == '\\'):
      buf += '\\\\'
    elif (i == '\n'):
      buf += '<br/>'
    elif (i == '"'):
      buf += '\\"'
    elif (i == ' '):
      buf += '&nbsp;'
    else:
      buf += i

  return buf


if __name__ != '__main__':
  sys.stderr.write("🚫  Incorrect usage\n")
  sys.exit(2)

try:
  opts, args = getopt.getopt(sys.argv[1:], 'v')
except getopt.GetoptError:
  sys.stderr.write("🚫  Incorrect usage\n")
  sys.exit(2)

if not args:
  args = []


body = ''
verbose = False

for opt, arg in opts:
  if opt == '-v':
    verbose = True

cmd = ''

if not sys.stdin.isatty():
  for line in sys.stdin:
    body += line


if len(args):
  for arg in args:
    cmd += "  set r to make new note at folder \"Notes\" with properties {name:\"" + esc(arg) + "\", body:\"" + esc(body) + "\"}\n"
else:
  cmd += " set r to make new note at folder \"Notes\" with properties { body:\"" + esc(body) + "\" }\n"

if len(args) or body:
  cmd = "tell application \"Notes\"\n" + cmd + "end tell\n"
  f = tempfile.NamedTemporaryFile(delete=False)
  f.write(cmd)

  if verbose:
    f.seek(0)
    sys.stdout.write("🍎")
    sys.stdout.write("  " + f.read().replace("\n", "\n   ").rstrip() + "\n")

  f.close()

  out,err = subprocess.Popen(["osascript", f.name], stdout=subprocess.PIPE).communicate()

else:
    sys.stderr.write("🚫  Nothing to make note of\n")
