#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Set the background color of a Terminal.app window via command-line
"""

# tell application "Terminal"
#   try
#     set current settings of selected tab of window 1 to (settings set "???")
#   on error
#     beep
#   end try
# end tell

import sys
import os
import getopt
import tempfile
import subprocess


def esc(arg):
  """
  Escapes a string's characters

  @param arg (string)
  @return string
  """

  buf = ''
  for i in arg:
    if (i == '\\'):
      buf += '\\\\'
    elif (i == '\n'):
      buf += '<br/>'
    elif (i == '"'):
      buf += '\\"'
    elif (i == ' '):
      buf += '&nbsp;'
    elif (i == '>'):
      buf += '&gt;'
    elif (i == '<'):
      buf += '&lt;'
    else:
      buf += i

  return buf


if __name__ != '__main__':
  sys.stderr.write("🚫  Incorrect usage\n")
  sys.exit(2)

try:
  opts, args = getopt.getopt(sys.argv[1:], 'v')
except getopt.GetoptError:
  sys.stderr.write("🚫  Incorrect usage\n")
  sys.exit(2)

verbose = False

for opt, arg in opts:
  if opt == '-v':
    verbose = True

if len(args) > 1:
  sys.stderr.write("🚫  Invalid Terminal setting specified: " + str(args) + "\n")
  sys.exit(2)
elif len(args) == 0:
  args = ["Pro"]

cmd = "  try\n    set current settings of selected tab of window 1 to (settings set \"" + args[0] + "\")\n  on error\n    beep\n  end try\n"
cmd = "tell application \"Terminal\"\n" + cmd + "end tell\n"
f = tempfile.NamedTemporaryFile(delete=False)
f.write(cmd)

if verbose:
  f.seek(0)
  sys.stdout.write("🍎")
  sys.stdout.write("  " + f.read().replace("\n", "\n   ").rstrip() + "\n")

f.close()

out,err = subprocess.Popen(["osascript", f.name], stdout=subprocess.PIPE).communicate()
