#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Create a reminder from the command-line

> todo "thing"
> todo -p "thing"                 # add priority
> todo -p -d "12/25/15" "thing"   # add priority and due date of Christmas Day 2015
> todo -p -d today "thing"        # add priority and due date of today
> todo -p -d tomorrow "thing"     # add priority and due date of tomorrow
> cat foo.txt | todo "hi"         # create a note whose body is the contents of foo.txt

"""

# tell application "Reminders"
#  set newreminder to make new reminder
#  set name of newreminder to "buh"
#  set body of newreminder to "ok"
#  set due date of r to date "12/25/04"
#  set remind me date of r to date "12/24/14"
#  set priority of r to 0
# end tell

import sys
import os
import getopt
import tempfile
import subprocess
import datetime


def esc(arg):

  buf = ''
  for i in arg:
    if (i == '\\'):
      buf += '\\\\'
    elif (i == '"'):
      buf += '\\"'
    elif (i == '\n'):
      buf += '\\n'
    else:
      buf += i

  return buf

if __name__ != '__main__':
  sys.stderr.write("🚫  Incorrect usage\n")
  sys.exit(2)

try:
  opts, args = getopt.getopt(sys.argv[1:], 'vpd:')
except getopt.GetoptError:
  sys.stderr.write("🚫  Incorrect usage\n")
  sys.exit(2)

if not args:
  args = []

TODAY = ['today']
TOMORROW = ['tomorrow']


body = ''
due = None
priority = None
verbose = False

for opt, arg in opts:
  if opt == '-v':
    verbose = True
  if opt == '-d':
    due = arg
  if opt == '-p':
    priority = True


if not sys.stdin.isatty():
  for line in sys.stdin:
    body += line


cmd = ''

for arg in args:

  cmd += "  set r to make new reminder\n"
  cmd += "  set name of r to \"" + esc(arg) + "\"\n"

  if due:
    if due in TODAY:
      cmd += "  set due date of r to current date\n"
    elif due in TOMORROW:
      cmd += "  set tomorrow to (current date) + (24 * 60 * 60)\n  set due date of r to date (date string of tomorrow)\n"
    else:
      cmd += "  set due date of r to date \"" + str(due) + "\"\n"

  if body:
    cmd += " set body of r to \"" + esc(body) + "\"\n" 

  if priority:
    cmd += "  set priority of r to 1\n"

if len(args):
  cmd = "tell application \"Reminders\"\n" + cmd + "end tell\n"
  f = tempfile.NamedTemporaryFile(delete=False)

  f.write(cmd)

  if verbose:
    f.seek(0)
    sys.stdout.write("🍎")
    sys.stdout.write("  " + f.read().replace("\n", "\n   ").rstrip() + "\n")

  f.close()

  out,err = subprocess.Popen(["osascript", f.name], stdout=subprocess.PIPE).communicate()

else:
  sys.stderr.write("🚫  Nothing to do\n")
